use pedidos;

INSERT INTO CLIENTE(TIPO,DOCUMENTO,NOME)VALUES('pf','123456','natasha');
INSERT INTO CLIENTE(TIPO,DOCUMENTO,NOME)VALUES('pf','123562','Carol');
INSERT INTO CLIENTE(TIPO,DOCUMENTO,NOME)VALUES('pj','123455556','Paula');
INSERT INTO CLIENTE(TIPO,DOCUMENTO,NOME)VALUES('pf','562486','Giovanna');

INSERT INTO PEDIDO(DATA,CLIENTE_ID,SITUACAO,VALOR_TOTAL,BAIRRO,CEP,CIDADE,ESTADO,NUMERO,RUA)VALUES('2021-01-01',1,TRUE,100,'Jd.Hortensias','123456-8','Rio do SuL','SC','33','Giacomo Busnardo');
INSERT INTO PEDIDO(DATA,CLIENTE_ID,SITUACAO,VALOR_TOTAL,BAIRRO,CEP,CIDADE,ESTADO,NUMERO,RUA)VALUES('2022-01-01',2,FALSE,200,'Federação','40230109','Salvador','bahia','168','Mata Maroto');
INSERT INTO PEDIDO(DATA,CLIENTE_ID,SITUACAO,VALOR_TOTAL,BAIRRO,CEP,CIDADE,ESTADO,NUMERO,RUA)VALUES('2021-04-01',3,TRUE,300,'Alto das Pombas','40230109','Salvador','bahia','16','Sobradinho');
INSERT INTO PEDIDO(DATA,CLIENTE_ID,SITUACAO,VALOR_TOTAL,BAIRRO,CEP,CIDADE,ESTADO,NUMERO,RUA)VALUES('2019-01-21',4,FALSE,400,'Cabula','40230111','Salvador','bahia','160','Sergio de Carvalho');

INSERT INTO PRODUTO(DESCRICAO,VALOR,STATUS)VALUES('livro44444',30.50,TRUE);
INSERT INTO PRODUTO(DESCRICAO,VALOR,STATUS)VALUES('Um Dia',50.00,FALSE);
INSERT INTO PRODUTO(DESCRICAO,VALOR,STATUS)VALUES('Gabriela',20.00,TRUE);
INSERT INTO PRODUTO(DESCRICAO,VALOR,STATUS)VALUES('Cerimônia Mortal',30.50,FALSE);

INSERT INTO ITENS_PEDIDO(QUANTIDADE_PRODUTO,PRODUTO_ID,PEDIDO_ID,VALOR_TOTAL)VALUES(1,1,1,23.50);
INSERT INTO ITENS_PEDIDO(QUANTIDADE_PRODUTO,PRODUTO_ID,PEDIDO_ID,VALOR_TOTAL)VALUES(4,2,2,500);
INSERT INTO ITENS_PEDIDO(QUANTIDADE_PRODUTO,PRODUTO_ID,PEDIDO_ID,VALOR_TOTAL)VALUES(3,3,3,400);
INSERT INTO ITENS_PEDIDO(QUANTIDADE_PRODUTO,PRODUTO_ID,PEDIDO_ID,VALOR_TOTAL)VALUES(2,4,4,500);

select * from CLIENTE e ;
select * from PEDIDO e ;
select * from PRODUTO e ;
select * from ITENS_PEDIDO e ;